"""add stored_path to study_materials

Revision ID: 3ad888cdab84
Revises: c41262fce575
Create Date: 2026-07-15 23:28:38.569544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad888cdab84'
down_revision: Union[str, Sequence[str], None] = 'c41262fce575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_materials', sa.Column('stored_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_materials', 'stored_path')
    # ### end Alembic commands ###
