"""add subject_id to study_materials

Revision ID: a3cbaba54a80
Revises: 9b21e19187e7
Create Date: 2026-07-23 23:22:58.908591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cbaba54a80'
down_revision: Union[str, Sequence[str], None] = '9b21e19187e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_materials', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'study_materials', 'subject_profiles', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_materials', type_='foreignkey')
    op.drop_column('study_materials', 'subject_id')
    # ### end Alembic commands ###
